# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_auto_20170216_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
